// Owner-supplied inventory. English display titles; language describes the owned edition.
// See data/catalog-sources.json and data/README.md for catalogue metadata and unresolved details.
export const collection = [
  {
    "id": "dancefloor",
    "title": "The Skirt Sings at the Landing",
    "originalTitle": "Légères sur le dancefloor",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 3,
    "ownedRange": "1–3",
    "image": "dancefloor.webp",
    "totalVolumes": 6,
    "href": "https://anilist.co/manga/122993",
    "linkLabel": "View on AniList",
    "edition": "Box set 1 · volumes 1–3",
    "titleNote": "Common English catalogue title; no official English edition identified."
  },
  {
    "id": "boys-abyss",
    "title": "Boy’s Abyss",
    "originalTitle": "Boy’s Abyss",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 18,
    "ownedRange": "1–18",
    "image": "boys-abyss.jpg",
    "totalVolumes": 18,
    "href": "https://anilist.co/manga/116186",
    "linkLabel": "View on AniList"
  },
  {
    "id": "assorted-entanglements",
    "title": "Assorted Entanglements",
    "originalTitle": "Nos différences enlacées",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 8,
    "ownedRange": "1–8",
    "image": "assorted-entanglements.webp",
    "totalVolumes": 10,
    "href": "https://anilist.co/manga/108070",
    "linkLabel": "View on AniList"
  },
  {
    "id": "dying-day",
    "title": "I Want to Love You Till Your Dying Day",
    "originalTitle": "Je veux t’aimer jusqu’à ta mort",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 7,
    "ownedRange": "1–7",
    "image": "dying-day.webp",
    "totalVolumes": null,
    "href": "https://anilist.co/manga/104045",
    "linkLabel": "View on AniList"
  },
  {
    "id": "monster",
    "title": "This Monster Wants to Eat Me",
    "originalTitle": "This Monster Wants to Eat Me",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 7,
    "ownedRange": "1–7",
    "image": "monster.webp",
    "totalVolumes": null,
    "href": "https://anilist.co/manga/123777",
    "linkLabel": "View on AniList"
  },
  {
    "id": "rainy-night",
    "title": "The Moon on a Rainy Night",
    "originalTitle": "The Moon on a Rainy Night",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 3,
    "ownedRange": "1–3",
    "image": "rainy-night.webp",
    "totalVolumes": null,
    "href": "https://anilist.co/manga/136109",
    "linkLabel": "View on AniList"
  },
  {
    "id": "sisters-friend",
    "title": "My Sister’s Best Friend, My Lover.",
    "originalTitle": "Le Poids du silence",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 2,
    "ownedRange": "1–2",
    "image": "sisters-friend.webp",
    "totalVolumes": 4,
    "href": "https://anilist.co/manga/136609",
    "linkLabel": "View on AniList",
    "titleNote": "English translated catalogue title."
  },
  {
    "id": "married-friend",
    "title": "I Married My Female Friend",
    "originalTitle": "Mariée à ma meilleure amie",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 3,
    "ownedRange": "1–3",
    "image": "married-friend.webp",
    "totalVolumes": 4,
    "href": "https://anilist.co/manga/126292",
    "linkLabel": "View on AniList"
  },
  {
    "id": "sweet-guilty",
    "title": "Sweet Guilty Love Bites",
    "originalTitle": "Sweet Guilty Love Bites",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 1,
    "ownedRange": "1",
    "image": "sweet-guilty.webp",
    "totalVolumes": 1,
    "href": "https://anilist.co/manga/51138",
    "linkLabel": "View on AniList"
  },
  {
    "id": "yotsuba",
    "title": "Yotsuba&!",
    "originalTitle": "よつばと！",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "Japanese",
    "ownedVolumes": 3,
    "ownedRange": "1–3",
    "image": "yotsuba.webp",
    "totalVolumes": null,
    "href": "https://anilist.co/manga/30104",
    "linkLabel": "View on AniList"
  },
  {
    "id": "goodbye-eri",
    "title": "Goodbye, Eri",
    "originalTitle": "Adieu Eri",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 1,
    "ownedRange": "1",
    "image": "goodbye-eri.webp",
    "totalVolumes": 1,
    "href": "https://anilist.co/manga/146983",
    "linkLabel": "View on AniList"
  },
  {
    "id": "fujimoto-22-26",
    "title": "Tatsuki Fujimoto Before Chainsaw Man: 22–26",
    "originalTitle": "22–26",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 1,
    "ownedRange": "1",
    "image": "fujimoto-22-26.webp",
    "totalVolumes": 1,
    "href": "https://anilist.co/manga/141157",
    "linkLabel": "View on AniList"
  },
  {
    "id": "divine-comedy",
    "title": "The Divine Comedy",
    "originalTitle": "La Divine Comédie",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 1,
    "ownedRange": "1",
    "image": "divine-comedy.webp",
    "totalVolumes": 1,
    "publisher": "Soleil Manga",
    "edition": "Classics in Manga",
    "isbn": "9782302064300",
    "creator": "Variety Artworks · Dante Alighieri"
  },
  {
    "id": "summer",
    "title": "Throw Away the Suit Together",
    "originalTitle": "Un été vers l’inconnu avec toi",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 3,
    "ownedRange": "1–3",
    "image": "summer.webp",
    "totalVolumes": 3,
    "href": "https://anilist.co/manga/136774",
    "linkLabel": "View on AniList"
  },
  {
    "id": "love-triangle",
    "title": "An Easy Introduction to Love Triangles (To Pass the Exam!)",
    "originalTitle": "Introduction au théorème du triangle amoureux",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 1,
    "ownedRange": "1",
    "image": "love-triangle.webp",
    "totalVolumes": 2,
    "href": "https://anilist.co/manga/114970",
    "linkLabel": "View on AniList",
    "titleNote": "English translated catalogue title."
  },
  {
    "id": "wishing-star",
    "title": "There Is No Love Wishing Upon a Star",
    "originalTitle": "Constellations cruelles",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 1,
    "ownedRange": "1",
    "image": "wishing-star.webp",
    "totalVolumes": 5,
    "href": "https://anilist.co/manga/159925",
    "linkLabel": "View on AniList",
    "titleNote": "Common English catalogue title; no official English edition identified."
  },
  {
    "id": "wasnt-a-guy",
    "title": "The Guy She Was Interested In Wasn’t a Guy at All",
    "originalTitle": "She Wasn’t a Guy",
    "category": "manga",
    "format": "Paperback",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 3,
    "ownedRange": "1–3",
    "image": "wasnt-a-guy.webp",
    "totalVolumes": null,
    "href": "https://anilist.co/manga/149544",
    "linkLabel": "View on AniList"
  },
  {
    "id": "same-dream",
    "title": "I Had That Same Dream Again",
    "originalTitle": null,
    "category": "light-novels",
    "format": "Novel",
    "status": "owned",
    "language": "English",
    "ownedVolumes": 1,
    "ownedRange": "1",
    "image": "same-dream.webp",
    "totalVolumes": 1,
    "href": "https://sevenseasentertainment.com/books/i-had-that-same-dream-again-novel/",
    "linkLabel": "Publisher page"
  },
  {
    "id": "sayaka",
    "title": "Bloom Into You: Regarding Saeki Sayaka",
    "originalTitle": null,
    "category": "light-novels",
    "format": "Light novel",
    "status": "owned",
    "language": "English",
    "ownedVolumes": 3,
    "ownedRange": "1–3",
    "image": "sayaka.webp",
    "totalVolumes": 3,
    "href": "https://anilist.co/manga/105388",
    "linkLabel": "View on AniList"
  },
  {
    "id": "garden-words",
    "title": "The Garden of Words",
    "originalTitle": "The Garden of Words",
    "category": "manga",
    "format": "Manga + novel",
    "status": "owned",
    "language": "French",
    "ownedVolumes": 2,
    "ownedRange": null,
    "image": "garden-words.webp",
    "categories": [
      "manga",
      "light-novels"
    ],
    "totalVolumes": 2,
    "edition": "Limited collector’s box set",
    "contents": "1 manga + 1 novel",
    "publisher": "Kazé",
    "href": "https://www.manga-news.com/index.php/manga/Garden-of-words-Coffret",
    "linkLabel": "Edition details"
  },
  {
    "id": "saber-last-episode",
    "title": "Artoria Pendragon: Last Episode",
    "category": "figurines",
    "format": "Painted figure",
    "status": "owned",
    "manufacturer": "WING",
    "scale": "1/8",
    "image": "saber-last-episode.webp",
    "href": "https://www.goodsmile.info/en/product/4809",
    "linkLabel": "Product page"
  },
  {
    "id": "saber-pajamas",
    "title": "Artoria Pendragon: Pajamas Version",
    "category": "figurines",
    "format": "Painted figure",
    "status": "owned",
    "manufacturer": "WING",
    "scale": "1/7",
    "image": "saber-pajamas.webp",
    "href": "https://figurememo.com/product/fate-zero-altria-pendragon-1-7-saber-pajama-ver-wing",
    "linkLabel": "Product page"
  },
  {
    "id": "saber-winter",
    "title": "Artoria Pendragon: Winter Night",
    "category": "figurines",
    "format": "Figure",
    "status": "owned",
    "manufacturer": "QuietArt Studio",
    "scale": "1/6",
    "image": "saber-winter.webp",
    "href": "https://www.orzgk.com/product/quietart-studio-artoria-pendragon-winter-night-fate-stay-night/",
    "linkLabel": "Product page"
  },
  {
    "id": "saber-avalon",
    "title": "Saber: Garden of Avalon",
    "originalTitle": "セイバー -Garden of Avalon-",
    "category": "figurines",
    "format": "Painted figure",
    "status": "owned",
    "manufacturer": "Good Smile Company",
    "scale": "1/7",
    "image": "saber-avalon.webp",
    "href": "https://www.goodsmile.com/en/product/57700",
    "linkLabel": "Product page"
  },
  {
    "id": "fate-anniversary",
    "title": "Fate/stay night + Fate/hollow ataraxia",
    "category": "misc",
    "format": "Game box set",
    "status": "owned",
    "edition": "Fate 15th Anniversary Celebration Project",
    "condition": "Sealed",
    "image": "fate-anniversary.webp"
  },
  {
    "id": "artoria-painting",
    "title": "Artoria Pendragon: Ukiyo-e Woodblock Print",
    "category": "misc",
    "format": "Framed woodblock print",
    "status": "owned",
    "edition": "Limited to 300 copies",
    "technique": "Hand-carved, hand-printed ukiyo-e",
    "image": "artoria-painting.webp",
    "href": "https://www.ukiyoework.com/view/item/000000000172?category_page_id=fgo",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-birthday-2024-panel",
    "title": "Nakiri Ayame: Holographic Acrylic Panel",
    "category": "vtuber-merch",
    "format": "Acrylic panel",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2024",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2024-panel-owned.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-celebration-2024-holographic-acrylic-panel",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-birthday-2024-keychain",
    "title": "Nakiri Ayame: Shrine Maiden Plush Keychain",
    "category": "vtuber-merch",
    "format": "Plush keychain",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2024",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2024-keychain-owned.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-celebration-2024-plushie-keychain-shrine-maiden-ver",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-birthday-2024-bag",
    "title": "Nakiri Ayame: Nakiri Gang’s Crossbody Bag",
    "category": "vtuber-merch",
    "format": "Crossbody bag",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2024",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2024-bag.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-celebration-2024-nakiri-gangs-crossbody-bag",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-birthday-2024-towel",
    "title": "Nakiri Ayame: Poyoyo Hooded Towel",
    "category": "vtuber-merch",
    "format": "Hooded towel",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2024",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2024-towel.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-celebration-2024-poyoyo-hoodie-towel",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-birthday-2024-card",
    "title": "Nakiri Ayame: Birthday 2024 Autographed Card",
    "category": "vtuber-merch",
    "format": "Cheki-style card",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2024",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2024-card-owned.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-celebration-2024-merch-complete-set-limited-edition?variant=47563744477430",
    "linkLabel": "Set details",
    "signature": "Handwritten autograph"
  },
  {
    "id": "ayame-girly-plush",
    "quantity": 2,
    "title": "Nakiri Ayame: Girly Outfit",
    "category": "vtuber-merch",
    "format": "Plushie",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "image": "ayame-girly-plush-owned.webp",
    "href": "https://shop.geekjack.net/products/hololive-friends-with-u-nakiri-ayame-girly-outfit?variant=48206041776374",
    "linkLabel": "Product page",
    "edition": "hololive friends with u"
  },
  {
    "id": "ayame-kindergarten-puppet",
    "title": "Nakiri Ayame: Kindergarten Uniform Puppet Plush",
    "category": "vtuber-merch",
    "format": "Puppet plush",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "manufacturer": "FuRyu",
    "variant": "Kindergarten uniform",
    "size": "Approx. 25 cm",
    "edition": "2024",
    "image": "ayame-kindergarten-puppet-owned.webp",
    "href": "https://www.navitoworld.com/products/hololive-production-furyu-puppet-plush-toy?variant=49468361474335",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-anniversary-7-screen",
    "title": "Nakiri Ayame: Desktop Folding Screen",
    "category": "vtuber-merch",
    "format": "Folding screen",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 7th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-7-screen.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-7th-anniversary-desktop-folding-screen",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-anniversary-7-teacup",
    "title": "Nakiri Ayame: 7th Anniversary Teacup",
    "category": "vtuber-merch",
    "format": "Teacup",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 7th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-7-teacup.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-7th-anniversary-teacup",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-anniversary-7-fan",
    "title": "Nakiri Ayame: Folding Fan",
    "category": "vtuber-merch",
    "format": "Folding fan",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 7th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-7-fan.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-7th-anniversary-folding-fan",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-anniversary-7-light",
    "title": "Nakiri Ayame: Desktop Light",
    "category": "vtuber-merch",
    "format": "Light",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 7th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-7-light.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-7th-anniversary-desktop-light",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-anniversary-7-card",
    "title": "Nakiri Ayame: 7th Anniversary Autographed Card",
    "category": "vtuber-merch",
    "format": "Postcard",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 7th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-7-card-owned.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-7th-anniversary-merch-complete-set-limited-edition?variant=49028774658294",
    "linkLabel": "Set details",
    "signature": "Handwritten autograph",
    "message": "Foil-stamped message"
  },
  {
    "id": "ayame-plush",
    "title": "Nakiri Ayame: hololive friends with u",
    "category": "vtuber-merch",
    "format": "Plushie",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "image": "ayame-plush-owned.webp",
    "href": "https://shop.geekjack.net/products/hololive-friends-with-u-nakiri-ayame-re?variant=46472630010102",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-to-go",
    "title": "Nakiri Ayame: hololive friends to Go",
    "category": "vtuber-merch",
    "format": "Plush keychain",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "image": "ayame-to-go-owned.webp",
    "href": "https://shop.geekjack.net/products/hololive-friends-to-go-gen-2?variant=47033106039030",
    "linkLabel": "Product page",
    "variant": "Nakiri Ayame"
  },
  {
    "id": "ayame-birthday-2025-tapestry",
    "title": "Nakiri Ayame: Birthday 2025 B2 Tapestry",
    "category": "vtuber-merch",
    "format": "Tapestry",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2025",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2025-tapestry.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-2025-b2-tapestry",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-birthday-2025-shirt",
    "title": "Nakiri Ayame: Birthday 2025 T-Shirt",
    "category": "vtuber-merch",
    "format": "T-shirt",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2025",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2025-shirt.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-2025-t-shirt",
    "linkLabel": "Product page",
    "size": "One size"
  },
  {
    "id": "ayame-birthday-2025-cushion",
    "title": "Nakiri Ayame: Face Cushion",
    "category": "vtuber-merch",
    "format": "Cushion",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2025",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2025-cushion.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-2025-ayame-face-cushion",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-birthday-2025-eyewear",
    "title": "Nakiri Ayame: Poyoyo Eyewear Stand",
    "category": "vtuber-merch",
    "format": "Eyewear stand",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2025",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2025-eyewear.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-2025-poyoyo-eyewear-stand",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-birthday-2025-card",
    "title": "Nakiri Ayame: Birthday 2025 Autographed Card",
    "category": "vtuber-merch",
    "format": "Postcard",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame Birthday 2025",
    "edition": "From the limited-edition complete set",
    "image": "ayame-birthday-2025-card-owned.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-birthday-2025-merch-complete-set-limited-edition?variant=49782882402550",
    "linkLabel": "Set details",
    "signature": "Handwritten autograph",
    "message": "Foil-stamped message"
  },
  {
    "id": "ayafubumi-new-year",
    "title": "AyaFubuMi: Laid-Back New Year",
    "category": "vtuber-merch",
    "format": "Acrylic panel",
    "status": "owned",
    "talent": "AyaFubuMi",
    "image": "ayafubumi-new-year-owned.webp",
    "href": "https://shop.geekjack.net/products/ayafubumis-laid-back-new-year-merchandise-acrylic-panel?variant=45778933678326",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-pixel-shirt",
    "title": "Nakiri Ayame: hololive Connect Pixel Art",
    "category": "vtuber-merch",
    "format": "T-shirt",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "image": "ayame-pixel-shirt.webp",
    "href": "https://shop.geekjack.net/products/hololive-connect-hololive-pixel-art-generation-2-colored-ver-t-shirt?variant=47682306375926",
    "linkLabel": "Product page",
    "edition": "Generation 2 · Colored version",
    "size": "L"
  },
  {
    "id": "ayame-hoodie",
    "title": "Nakiri Ayame: Ido Original Design",
    "category": "vtuber-merch",
    "format": "Hoodie",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "image": "ayame-hoodie.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-re-released-edition-merch-hoodie-re-released-edition?variant=49904087793910",
    "linkLabel": "Product page",
    "edition": "Re-released edition",
    "size": "One size"
  },
  {
    "id": "ayafubumi-song-stand",
    "title": "Nakiri Ayame: AyaFubuMi New Song Release",
    "category": "vtuber-merch",
    "format": "Acrylic stand",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "image": "ayafubumi-song-stand-owned.webp",
    "href": "https://shop.geekjack.net/products/ayafubumi-new-song-release-commemoration-acrylic-stand?variant=50113882063094",
    "linkLabel": "Product page",
    "variant": "Nakiri Ayame"
  },
  {
    "id": "ayame-anniversary-8-mirror",
    "title": "Nakiri Ayame: 8th Anniversary Pub Mirror",
    "category": "vtuber-merch",
    "format": "Framed mirror",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 8th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-8-mirror.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-8th-anniversary-8th-anniversary-pub-mirror",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-anniversary-8-guards",
    "title": "Nakiri Ayame: Asura & Rakshasa Sword Guards",
    "category": "vtuber-merch",
    "format": "Sword guard pair",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 8th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-8-guards.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-8th-anniversary-sword-guard-asura-and-rakshasa",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-anniversary-8-pouch",
    "title": "Nakiri Ayame: Standard Outfit Drawstring Pouch",
    "category": "vtuber-merch",
    "format": "Drawstring pouch",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 8th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-8-pouch.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-8th-anniversary-standard-outfit-motif-drawstring-pouch",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-anniversary-8-purse",
    "title": "Nakiri Ayame: Celestial Maiden Coin Purse",
    "category": "vtuber-merch",
    "format": "Coin purse",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 8th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-8-purse.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-8th-anniversary-celestial-maiden-outfit-motif-coin-purse",
    "linkLabel": "Product page"
  },
  {
    "id": "ayame-anniversary-8-card",
    "title": "Nakiri Ayame: 8th Anniversary Autographed Card",
    "category": "vtuber-merch",
    "format": "Postcard",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "setName": "Nakiri Ayame 8th Anniversary",
    "edition": "From the limited-edition complete set",
    "image": "ayame-anniversary-8-card.webp",
    "href": "https://shop.geekjack.net/products/nakiri-ayame-8th-anniversary-merch-complete-set-limited-edition?variant=51572937851126",
    "linkLabel": "Set details",
    "signature": "Handwritten autograph",
    "message": "Foil-stamped message"
  },
  {
    "id": "ayame-anniversary-3-card",
    "title": "Nakiri Ayame: 3rd Anniversary Postcard",
    "category": "vtuber-merch",
    "format": "Postcard",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "edition": "3rd Anniversary · 2021",
    "image": "ayame-anniversary-3-card-owned.webp",
    "note": "Illustration by Nana Kagura. Released with handwritten and foil-stamped signature variants.",
    "href": "https://hololive.booth.pm/items/3314916",
    "linkLabel": "Release details",
    "signature": "Gold signature"
  },
  {
    "id": "ayame-birthday-2020-card",
    "title": "Nakiri Ayame: Birthday 2020 Postcard",
    "category": "vtuber-merch",
    "format": "Postcard",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "edition": "Birthday Celebration · 2020",
    "image": "ayame-birthday-2020-card-owned.webp",
    "note": "Illustration by Nana Kagura. The photographed copy also carries a thank-you message. Released with handwritten and foil-stamped signature variants.",
    "href": "https://hololive.booth.pm/items/2586180",
    "linkLabel": "Release details",
    "signature": "Gold signature"
  },
  {
    "id": "ayame-anniversary-2-letter",
    "title": "Nakiri Ayame: 2nd Anniversary Letter",
    "category": "vtuber-merch",
    "format": "Letter",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "edition": "2nd Anniversary · 2020",
    "image": "ayame-anniversary-2-letter-owned.webp",
    "href": "https://hololive.booth.pm/items/2309046",
    "linkLabel": "Release details",
    "message": "Printed reproduction of a handwritten message",
    "note": "Bonus letter included with the 2nd Anniversary voice full set. A separate item from the illustrated postcards."
  },
  {
    "id": "ayame-onikawaii-stand",
    "title": "Nakiri Ayame: ONIKAWAII Project in animate",
    "manufacturer": "Movic",
    "edition": "ONIKAWAII Project in animate",
    "href": "https://www.animate.co.jp/onlyshop/35581/",
    "category": "vtuber-merch",
    "format": "Acrylic stand",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "linkLabel": "Product page",
    "image": "ayame-onikawaii-stand-owned.webp"
  },
  {
    "id": "ayame-fun-day-out-stand",
    "title": "Nakiri Ayame: A Fun Day Out!",
    "edition": "Situation hololive · A Fun Day Out! vol. 3",
    "href": "https://shop.hololivepro.com/en/products/situationhololive_afundayout_vol3?variant=44509428056284",
    "category": "vtuber-merch",
    "format": "Acrylic stand",
    "status": "owned",
    "talent": "Nakiri Ayame",
    "linkLabel": "Product page",
    "image": "ayame-fun-day-out-stand-owned.webp"
  },
  {
    "id": "saber-gift-plush",
    "title": "Fate/stay night Heaven’s Feel: Special Gift Plush Saber",
    "category": "misc",
    "format": "Plushie",
    "status": "wishlist",
    "manufacturer": "Gift",
    "size": "Approx. 20 cm seated",
    "image": "saber-gift-plush.webp",
    "href": "https://www.gift-gift.jp/nui/nui547.html",
    "linkLabel": "Product page"
  }
];
